version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: jc
      MYSQL_PASSWORD: toor
    container_name: mydb
    volumes:
      - db_data:/var/lib/mysql

  php-apache:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    container_name: myphp
    volumes:
      - ./:/var/www/html 
volumes:
  db_data:  

  
